spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  tomcat:
    max-threads: 1

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG